#!/bin/sh

awk '$1 == "'$IFACE'" { print $2 }' /etc/network/aliases | while read ipaddr; do
	if [ `basename $0` = 'up-aliases' ]; then
		ip addr show dev $IFACE | grep -q "$ipaddr" || ip addr add "$ipaddr" dev $IFACE
	else
		ip addr show dev $IFACE | grep -q "$ipaddr" && ip addr del "$ipaddr" dev $IFACE
	fi
done
